name: Reusable deploy workflow

on:
  workflow_call:
    inputs:
      pulumi_stack_name:
        description: The Pulumi stack to deploy to
        required: true
        type: string
      docker_tag:
        description: The Docker tag to use for the deployment
        required: true
        type: string
    secrets:
      azure_client_id:
        description: The Azure client ID to deploy to
        required: true
      azure_tenant_id:
        description: The Azure tenant ID to deploy to
        required: true
      azure_subscription_id:
        description: The Azure subscription ID to deploy to
        required: true

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Pulumi CLI
        uses: pulumi/actions@v6
        with:
          pulumi-version: latest
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}
      - name: Deploy to Azure with Pulumi
        working-directory: pulumi
        run: |
          pulumi login
          pulumi stack select ${{ inputs.pulumi_stack_name }}
          pulumi config set imageTag ${{ inputs.docker_tag }}
          pulumi up --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
